# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y

# Allow modifying the OLED widgets
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Widget documentation from
# - https://github.com/mctechnology17/zmk-nice-oled#general-configuration
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
